title: Chi Zhang # your name (or website title) here
logo: "/images/selfie.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master Student in Urban Spatial Analytics, University of Pennsylvania
  <br><br>
  Bachelor of Engineering in Urban Planning and Design 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
